name: deploy docker

on: [ push ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Login to container
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            ghcr.io/oligkondr/crud_v3_ts:latest

