name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oligkondr/crud_v3_ts:latest

#      - name: Deploy to production
#        uses: appleboy/ssh-action@master
#        with:
#          username: ${{ secrets.SSH_USERNAME }}
#          host: ${{ secrets.SSH_HOST }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
##          script: 'cd /home/oleg/projects/crud_v3_ts && ./server_deploy.sh'
#          script: '/home/oleg/projects/crud_v3_ts/server_deploy.sh'
