name: test_crud

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Run tests
        run: php artisan test
