name: test_crud

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Composer dependencies
      - uses: shivammathur/setup-php@v2
      - run: composer install --prefer-dist
      - name: Run tests
        run: php vendor/bin/phpunit
